included:
  - Huequaliser
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - explicit_init
  - explicit_top_level_acl
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  # - attributes
  # - explicit_type_interface
  # - trailing_closure
  # - explicit_acl
disabled_rules:
  - strict_fileprivate
  - switch_case_alignment
  - superfluous_disable_command
  - operator_whitespace

identifier_name:
  excluded:
    - id
    - ID
    - x
    - y
    - z
    - i
    - a
    - b
    - c
line_length: 120
large_tuple: 3
number_separator:
  minimum_length: 5
type_name:
  excluded:
    - E
    - T
