#!/usr/bin/env bash
#
# Downloads and builds carthage dependencies

set -euo pipefail
IFS=$'\n\t'

cd "${0%/*}/.."

#    --new-resolver \
carthage update \
    --platform ios \
    --no-use-binaries \
    $@

rm -rf Carthage/Build/iOS/ReactiveSwift*
rm -rf Carthage/Build/iOS/ReactiveMoya*
