#!/usr/bin/env bash
#
# Downloads and builds carthage dependencies

set -euo pipefail
IFS=$'\n\t'

cd "${0%/*}/.."

#    --new-resolver \
    # --no-use-binaries \

carthage bootstrap \
    --platform ios \
    $@
