#!/usr/bin/env bash
#
# Linting and formatting source files

set -euo pipefail
IFS=$'\n\t'

cd "${0%/*}/.."

swiftlint autocorrect --quiet

swiftformat Huequaliser \
            --indent 4 \
            --indentcase true \
            --wrapelements beforefirst \
            --commas inline \
            --disable indent

swiftlint lint --quiet
